# Tomcat
server:
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

storage:
  enabled: true
  config:
    # 存储类型：local、aliyun
    type: local
    # 访问域名
    domain: http://localhost:8080
    # 配置访问前缀
    prefix:
  local:
    # 本地上传路径
    path: D://upload

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.wu.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE